# Generated by Django 4.1 on 2022-08-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='car_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='car_slug',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
